// Generated by Nexen Guide — universal Suspense fallback shown while
// a route segment compiles. Replaced (via React behaviour, not file
// overwrite) by the real page once the route's components mount.
import { PageSkeleton } from '../components/PageSkeleton';

export default function Loading() {
	return <PageSkeleton />;
}
