// Generated by Nexen Guide — fallback for routes the frontend stage
// has not yet produced. As the generator writes each page, the route
// becomes a real page.tsx and this fallback stops applying.
import { PageSkeleton } from '../components/PageSkeleton';

export default function NotFound() {
	return <PageSkeleton variant="coming-soon" />;
}
