// Generated by Nexen Guide.
//
// Self-contained app-shell shimmer (top bar + sidebar + card grid + table) shown
// while a route compiles (via app/loading.tsx) or doesn't yet exist on disk (via
// app/not-found.tsx). 100% inline styles — no Tailwind / globals.css dependency —
// so it can never render as a blank white screen before the CSS pipeline is ready.
// Listens for postMessage from the parent webview so the label flips in real time:
//
//   window.parent.postMessage({ type: 'nexen.page-status',
//                               route: '/dashboard',
//                               status: 'generating' }, '*')
//
// Status values: 'pending' (default) | 'generating' | 'ready'. 'ready' fades the
// skeleton out so the real page (if it has rendered behind us via Suspense) shows.
'use client';
import { useEffect, useState } from 'react';

interface Props {
	variant?: 'loading' | 'coming-soon';
}

type Status = 'pending' | 'generating' | 'ready';

const ACCENT = '#6366f1';
const shimmer = {
	borderRadius: 8,
	background: 'linear-gradient(90deg,#e9ebee 0%,#f4f5f7 50%,#e9ebee 100%)',
	backgroundSize: '800px 100%',
	animation: 'nexen-shimmer 1.5s linear infinite',
};
const surface = { background: '#ffffff', border: '1px solid #eceef1', borderRadius: 12 };

export function PageSkeleton({ variant = 'loading' }: Props) {
	const [status, setStatus] = useState<Status>('pending');
	const [route, setRoute] = useState<string>('');

	useEffect(() => {
		if (typeof window === 'undefined') return;
		setRoute(window.location.pathname || '/');
		const onMsg = (ev: MessageEvent) => {
			const data = ev.data as { type?: string; route?: string; status?: Status } | undefined;
			if (!data || data.type !== 'nexen.page-status') return;
			if (!data.route) return;
			if (data.route !== window.location.pathname) return;
			if (data.status) setStatus(data.status);
		};
		window.addEventListener('message', onMsg);
		return () => window.removeEventListener('message', onMsg);
	}, []);

	const label =
		variant === 'coming-soon'
			? (status === 'generating' ? 'Generating this page…' : 'Coming soon — generating')
			: (status === 'generating' ? 'Generating…' : 'Loading…');
	const dot = status === 'generating' ? ACCENT : '#9ca3af';

	return (
		<div style={{ minHeight: '100vh', background: '#f6f7f9', color: '#111827', fontFamily: 'ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, sans-serif', opacity: status === 'ready' ? 0 : 1, transition: 'opacity 240ms ease-out' }}>
			<div style={{ height: 56, background: '#fff', borderBottom: '1px solid #eceef1', display: 'flex', alignItems: 'center', gap: 16, padding: '0 20px' }}>
				<div style={{ width: 26, height: 26, borderRadius: 8, background: ACCENT }} />
				<div style={{ ...shimmer, width: 104, height: 12 }} />
				<div style={{ flex: 1 }} />
				<div style={{ ...shimmer, width: 60, height: 12 }} />
				<div style={{ ...shimmer, width: 60, height: 12 }} />
				<div style={{ ...shimmer, width: 30, height: 30, borderRadius: '50%' }} />
			</div>
			<div style={{ display: 'flex', minHeight: 'calc(100vh - 56px)' }}>
				<div style={{ width: 224, background: '#fff', borderRight: '1px solid #eceef1', padding: 16, display: 'flex', flexDirection: 'column', gap: 6 }}>
					{[...Array(7)].map((_, i) => (
						<div key={i} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '9px 10px', borderRadius: 8, background: i === 0 ? ACCENT + '14' : 'transparent' }}>
							<div style={{ ...shimmer, width: 18, height: 18, borderRadius: 6 }} />
							<div style={{ ...shimmer, width: 68 + ((i * 11) % 44), height: 10 }} />
						</div>
					))}
				</div>
				<div style={{ flex: 1, padding: 28, display: 'flex', flexDirection: 'column', gap: 22 }}>
					<div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
						<div style={{ ...shimmer, width: 260, height: 26 }} />
						<div style={{ ...shimmer, width: 380, height: 12 }} />
					</div>
					<div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 16 }}>
						{[...Array(4)].map((_, i) => (
							<div key={i} style={{ ...surface, padding: 18, display: 'flex', flexDirection: 'column', gap: 12 }}>
								<div style={{ ...shimmer, width: 80, height: 10 }} />
								<div style={{ ...shimmer, width: 124, height: 26 }} />
								<div style={{ ...shimmer, width: 56, height: 10 }} />
							</div>
						))}
					</div>
					<div style={{ ...surface, overflow: 'hidden' }}>
						<div style={{ display: 'flex', alignItems: 'center', gap: 16, padding: '16px 20px', borderBottom: '1px solid #f0f1f3' }}>
							<div style={{ ...shimmer, width: 150, height: 14 }} />
							<div style={{ flex: 1 }} />
							<div style={{ ...shimmer, width: 96, height: 30, borderRadius: 8 }} />
						</div>
						{[...Array(6)].map((_, i) => (
							<div key={i} style={{ display: 'flex', alignItems: 'center', gap: 16, padding: '14px 20px', borderBottom: i === 5 ? 'none' : '1px solid #f4f5f7' }}>
								<div style={{ ...shimmer, width: 34, height: 34, borderRadius: '50%' }} />
								<div style={{ ...shimmer, width: (40 + ((i * 13) % 34)) + '%', height: 12 }} />
								<div style={{ flex: 1 }} />
								<div style={{ ...shimmer, width: 80, height: 12 }} />
								<div style={{ ...shimmer, width: 62, height: 20, borderRadius: 999 }} />
							</div>
						))}
					</div>
				</div>
			</div>
			<div style={{ position: 'fixed', bottom: 20, right: 20, display: 'flex', alignItems: 'center', gap: 10, background: '#fff', border: '1px solid #eceef1', borderRadius: 999, padding: '9px 15px', boxShadow: '0 6px 20px rgba(17,24,39,0.08)' }}>
				<span style={{ width: 9, height: 9, borderRadius: '50%', background: dot, animation: 'nexen-pulse 1.4s ease-in-out infinite' }} />
				<span style={{ fontSize: 13, color: '#4b5563' }}>{label}{route ? ' · ' + route : ''}</span>
			</div>
			<style>{`html,body{margin:0;padding:0}@keyframes nexen-shimmer{0%{background-position:-400px 0}100%{background-position:400px 0}}@keyframes nexen-pulse{0%,100%{opacity:.35}50%{opacity:1}}`}</style>
		</div>
	);
}
